PaddlePaddle/PaddleGAN

configs/cyclegan_cityscapes.yaml, configs/pix2pix_cityscapes.yaml, ppgan/datasets/builder.py, ppgan/engine/trainer.py, ppgan/models/cycle_gan_model.py, ppgan/models/generators/resnet.py, ppgan/models/pix2pix_model.py, ppgan/utils/filesystem.py
1. 添加benchmark提测所需的log输出
2. 完善多卡训练功能
3. 去除一些没用的注释和代码
=> for Benchmark test

applications/DAIN/pwcnet/pwcnet.py, applications/DeOldify/model.py, applications/RealSR/predict.py, applications/RealSR/sr_model.py, applications/run.sh, applications/tools/video-enhance.py
1. add realsr model
2. use correlation api in paddle
3. rm unused code
=> Add RealSR to applications

applications/DAIN/predict.py, applications/DAIN/util.py, applications/DeOldify/model.py, applications/DeOldify/predict.py, applications/EDVR/data.py, applications/EDVR/predict.py, applications/RealSR/predict.py
1. 去除冗余的代码
2. 使用进度条代替行打印，使得log更简洁
3. ffmpeg添加-y选项
=> Refine application code

ppgan/engine/trainer.py, ppgan/utils/timer.py
每隔self.log_interval打印这self.log_interval个batch时间的平均值。
=> Calculate the average time for benchmark.

ppgan/models/generators/mobile_resnet.py
=> add mobile resnet

configs/pix2pix_cityscapes.yaml, ppgan/models/cycle_gan_model.py, ppgan/models/pix2pix_model.py, ppgan/modules/init.py
=> Add init module

applications/first_order_model/configs/vox-256.yaml, applications/tools/first-order-demo.py, applications/tools/video-enhance.py, configs/cyclegan_cityscapes.yaml, configs/cyclegan_horse2zebra.yaml, configs/pix2pix_cityscapes.yaml, configs/pix2pix_cityscapes_2gpus.yaml, configs/pix2pix_facades.yaml, ppgan/datasets/paired_dataset.py, ppgan/datasets/transforms/__init__.py, ppgan/datasets/transforms/builder.py, ppgan/datasets/transforms/transforms.py, ppgan/datasets/unpaired_dataset.py, ppgan/models/builder.py, ppgan/models/pix2pix_model.py, ppgan/utils/animate.py
=> Reproduce transforms module

ppgan/models/pix2pix_model.py
2.0删除了to_variable api，先改为to_tensor.
=> Fix to_variable

ppgan/solver/lr_scheduler.py
=> Fix lr scheduler

ppgan/datasets/builder.py, ppgan/models/generators/resnet.py, ppgan/models/losses.py, ppgan/modules/init.py, ppgan/modules/norm.py
=> fix some apis to paddle-dev

ppgan/models/generators/deoldify.py
=> Fix pool2d api

docs/apis/apps.md, ppgan/apps/dain_predictor.py, ppgan/apps/deepremaster_predictor.py, ppgan/models/cycle_gan_model.py, ppgan/models/pix2pix_model.py
1. Add doc for Apps.
2. Remove key_frame_thread in DAIN.
3. change output_path to output to keep same with othere APIs.
=> Add doc for Apps and refine some code

README.md, README_en.md, data/download_cyclegan_data.py, data/download_pix2pix_data.py, docs/data_prepare.md, docs/data_prepare_en.md, docs/get_started.md, docs/get_started_en.md, docs/install.md, docs/install_en.md, docs/tutorials/video_restore.md, ppgan/apps/dain_predictor.py, ppgan/apps/deepremaster_predictor.py, ppgan/apps/deoldify_predictor.py, ppgan/apps/edvr_predictor.py, ppgan/apps/first_order_predictor.py, ppgan/apps/realsr_predictor.py, ppgan/utils/download.py, ppgan/utils/logger.py, script/pix2pix_download.sh
1. 统一数据集与权重的下载
2. 优化logger
3. 优化安装，数据准备文档
=> Refine codes and docs

ppgan/apps/first_order_predictor.py, ppgan/utils/download.py
=> Auto make output dir when use first_order_predictor

README_en.md
Made several changes:
- an -> a
- Realse -> Release
- Traning -> Training
- Unify application descriptions with noun.
=> Fix typographical error

applications/tools/video-enhance.py, docs/en_US/tutorials/video_restore.md, docs/zh_CN/apis/apps.md, docs/zh_CN/tutorials/video_restore.md, ppgan/apps/base_predictor.py, ppgan/apps/deoldify_predictor.py, ppgan/apps/realsr_predictor.py, ppgan/models/generators/deoldify.py, ppgan/models/pix2pix_model.py
1. Add art model of deoldify
2. fix is_img and save bug
=> Add art model of deoldify

ppgan/utils/logger.py
=> small fix logger

.vscode/settings.json, configs/dcgan_mnist.yaml, docs/en_US/install.md, docs/zh_CN/install.md, ppgan/models/__init__.py, ppgan/models/dc_gan_model.py, ppgan/models/discriminators/__init__.py, ppgan/models/discriminators/dcdiscriminator.py, ppgan/models/generators/__init__.py, ppgan/models/generators/dcgenerator.py
1. paddlepaddle2.0.0rc instruction for windows can be found from paddlepaddle main page
2. only two steps, install paddlepaddle and paddlegan, other than 3step
=> docs: update install instruction

ppgan/faceutils/face_detection/api.py, ppgan/faceutils/face_detection/detection/sfd/sfd_detector.py, ppgan/modules/conv.py
=> Fix some bugs.

docs/en_US/install.md, docs/zh_CN/install.md, ppgan/datasets/transforms/transforms.py, setup.py
=> Fix bugs and update docs

ppgan/datasets/transforms/__init__.py, ppgan/models/criterions/perceptual_loss.py, ppgan/utils/download.py
1. fix transform import error #114 
2. move get_logger to local function
3. update vgg19 url
=> Fix import error

configs/wgan_mnist.yaml, ppgan/datasets/common_vision_dataset.py, ppgan/engine/trainer.py, ppgan/models/base_model.py, ppgan/models/gan_model.py
=> Adapt wgan to new code structure

ppgan/datasets/unpaired_dataset.py
=> small bug fix

README.md, README_cn.md
=> Add photo2cartoon in README

ppgan/apps/base_predictor.py
=> Fix load_inference_model bug due to api changes

configs/cyclegan_cityscapes.yaml, configs/cyclegan_horse2zebra.yaml, configs/pix2pix_cityscapes.yaml, configs/pix2pix_cityscapes_2gpus.yaml, configs/pix2pix_facades.yaml, ppgan/apps/realsr_predictor.py, ppgan/engine/trainer.py, ppgan/utils/options.py, ppgan/utils/setup.py
1.更新部分配置文件
2.--config-file->-c
3.使用congfig文件名作为output dir.由于很多模型共享同一个类，使用类名作为output dir比较混乱。
4.修复权重重复保存的bug
5.apps中realsr模型推理时添加no_grad
=> Fix some bugs

configs/ugatit_photo2cartoon.yaml
将photo2cartoon 配置文件修改为paddlegan接受的格式。
=> fix photo2cartoon configs

README.md, README_cn.md, docs/en_US/tutorials/super_resolution.md
=> add a RS doc
